# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title: Xuanlin Zeng
url: https://xuanlinzeng.github.io
description: "Ph.D. Student at Tongji University. Focusing on multi-vehicle cooperative control, intelligent transportation systems, and autonomous driving."
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  G-3MF2DQ0TC0

# SEO Related
google_site_verification :  KRIKPcOy-YZOq5PXLDIEAmLQcqVMScbFWbDfokUkaNU
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Owner/author information
owner:
  name: Xuanlin Zeng
  avatar: android-chrome-512x512.png
  email: zengxuanlin@tongji.edu.cn
  cv: https://xuanlinzeng.github.io/file/CV-XuanlinZENG.pdf
 
  twitter: xuanlin_zeng
  github: XuanlinZeng
  linkedin: xuanlin-zeng
  scholar: https://scholar.google.com/citations?user=ueRm4q0AAAAJ
  bilibili: 94878011
  researchgate: https://www.researchgate.net/profile/Xuanlin-Zeng
  zhihu: https://www.zhihu.com/people/hungry-foolish-24-8
  # facebook: # 又被封了,"profile.php?id=61554372831369"
  instagram: zengxuanlin
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: # "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: Homepage
    url: /
  - title: Publications
    url: /publications/
  - title: Other Projects
    url: /other-projects/
  - title: Honors and Awards
    url: /honors-and-awards/
  - title: Services
    url: /services/
  - title: CV
    url: /cv/
  - title: Notes
    url: /notes/
  - title: Blogs
    url: /blogs/
  - title: Misc
    url: /misc/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
